backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)



collections:
  - name: 'pages'
  label: 'Pages'
  editor:
    preview: false
  files:
    - label: 'About Page'
      name: 'about'
      file: 'about.md'
      fields:
        - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
        - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
        - { label: 'Body', name: 'body', widget: 'markdown' }

media_folder: "public/assets/images" # Location where files will be stored in the repo
public_folder: "public/assets/images" # The src attribute for uploaded media



